### ISSUE TITLE
MPTS Stream wih multi service

### ISSUE THREAD

**Issue by sachin0606** [jacovis/Javi.FFmpeg#1]
Hi, Currently i want to transcode all the services in MPTS stream of UDP. using the below command and want to achive this wpf form. any guidance.

ffmpeg -re -i udp://224.2.2.8:1008 -map 0:p:40 -map 0:p:29 -map 0:p:42 -map 0:p:17 -map 0:p:19 -vcodec mpeg2video -s 720x576 -r 25 -flags cgop+ilme -sc_threshold 1000000000 -b:v 2M -minrate:v 2M -maxrate:v 2M -bufsize:v 1.4M -acodec mp2 -ac 2 -b:a 192k  -program title=xyz:st=0:st=1 -program title=zz:st=2:st=3 -program title=z2:st=4:st=5 -program title=SriShankara:st=6:st=7 -program title=Shubhvarta:st=8:st=9 -f mpegts udp://230.0.0.5:1008?pkt_size=1316

Like this have multi commands need to call and want to see the speed of this thread individually, how can i use this with your builds?

**Comment by jacovis** [comment]
Can you review the latest commit? I have deleted the input check on http:// or https:// or valid file, so your stream url should be accepted now as input to the Run method.
Also see the demo application, I have added your commandline as demo.

**Comment by sachin0606** [comment]
Thanks for the reply. Just amazing , just need to modify command. as local address attribute in FFMPEG needs double quote after -f . so below is the command variable. 
var cmd = " -i udp://224.2.2.8:1008 -map 0:p:40 -map 0:p:29 -map 0:p:42 -map 0:p:17 -map 0:p:19 -vcodec mpeg2video -s 720x576 -r 25 -flags cgop+ilme -sc_threshold 1000000000 -b:v 2M -minrate:v 2M -maxrate:v 2M -bufsize:v 1.4M -acodec mp2 -ac 2 -b:a 192k -program title=xyz:st=0:st=1 -program title=zz:st=2:st=3 -program title=z2:st=4:st=5 -program title=SriShankara:st=6:st=7 -program title=Shubhvarta:st=8:st=9 -f mpegts ""udp://230.0.0.5:1008?pkt_size=1316";

below are the some doubts and question: 
can we manage the output check, when its stop  output for perticular command , can we kill and start the process again??? and how many task i can manage within the server class machine. (sorry last question is noob question)

**Comment by jacovis** [comment]
If you look at the demo application, the code to convert audio to AC3 calls the .ConvertAudioAC3 extension method in a asynchronous Task Run and uses a CancellationTokenSource to be able to kill the process. Killing the process is done in the cancel button handler. I suggest you take a look at that if you really need to forcefully kill the ffmpeg process. 
About the number of tasks I can not really answer, this is also not really related to this package. I suggest studying yourself or ask a question on another board like stackoverflow.

**Comment by sachin0606** [comment]
Thanks. really helped me alot. thanks for the tool.

**Comment by jacovis** [comment]
My pleasure.
