### ISSUE TITLE
Waiting for Proccess to Finish

### ISSUE THREAD

**Issue by EuanHoll** [jacovis/Javi.FFmpeg#3]
The Wrapper doesn't seem to wait until ffmpeg is finished doing whatever it's doing before exiting. If you try use the ffmpeg.run like so 
`
ffmpeg.Run(input, str1, FinalVariables.CutCommand(input, str1, time, size, 0.25f));
ffmpeg.Run(str1, str2, FinalVariables.ReverseCommand(str1, str2, 0.25f));
`
it crashes because ffmpeg isn't finished making the first video before it gets used in the second function.

**Comment by jacovis** [comment]
I've tried to reproduce this using the following code in MainWindow.xaml.cs in the demo project in this solution:

        private void ButtonRun_Click(object sender, RoutedEventArgs e)
        {
            OutputText("***Start FFmpeg");

            using (var ffmpeg = new FFmpeg(FFmpegFileName))
            {
                ffmpeg.OnData += (s, args) => { OutputText(args.Data); };

                string inputFile = "Sample.mp4";
                string outputFile1 = "Sample.mkv";
                string outputFile2 = "Sample.flv";

                string commandLine = string.Format($"-i \"{inputFile}\" \"{outputFile1}\"");
                ffmpeg.Run(inputFile, outputFile1, commandLine);

                commandLine = string.Format($"-i \"{outputFile1}\" \"{outputFile2}\"");
                ffmpeg.Run(outputFile1, outputFile2, commandLine);
            }

            OutputText("***End FFmpeg");
        }


This runs as expected and does not crash. Can you try this code on your end? Can you do more testing into this behaviour?

**Comment by jacovis** [comment]
Close because no feedback.
